-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "retailPrice" DROP NOT NULL;
ALTER TABLE "Product" ALTER COLUMN "colorId" DROP NOT NULL;
ALTER TABLE "Product" ALTER COLUMN "conditionId" DROP NOT NULL;
ALTER TABLE "Product" ALTER COLUMN "materialId" DROP NOT NULL;
ALTER TABLE "Product" ALTER COLUMN "genderId" DROP NOT NULL;
