export function getCountryCode(countryName: string): string {
    const countryCodes: { [key: string]: string } = {
        "Australia": "AU",
        "Austria": "AT",
        "Belgium": "BE",
        "Brazil": "BR",
        "Bulgaria": "BG",
        "Canada": "CA",
        "Croatia": "HR",
        "Cyprus": "CY",
        "Czech Republic": "CZ",
        "Denmark": "DK",
        "Estonia": "EE",
        "Finland": "FI",
        "France": "FR",
        "Germany": "DE",
        "Ghana": "GH",
        "Gibraltar": "GI",
        "Greece": "GR",
        "Hong Kong": "HK",
        "Hungary": "HU",
        "India": "IN",
        "Indonesia": "ID",
        "Ireland": "IE",
        "Italy": "IT",
        "Japan": "JP",
        "Kenya": "KE",
        "Latvia": "LV",
        "Liechtenstein": "LI",
        "Lithuania": "LT",
        "Luxembourg": "LU",
        "Malaysia": "MY",
        "Malta": "MT",
        "Mexico": "MX",
        "Netherlands": "NL",
        "New Zealand": "NZ",
        "Nigeria": "NG",
        "Norway": "NO",
        "Poland": "PL",
        "Portugal": "PT",
        "Romania": "RO",
        "Singapore": "SG",
        "Slovakia": "SK",
        "Slovenia": "SI",
        "South Africa": "ZA",
        "Spain": "ES",
        "Sweden": "SE",
        "Switzerland": "CH",
        "Thailand": "TH",
        "United Arab Emirates": "AE"
    };

    return countryCodes[countryName] || "We don't support this country";
}
